services:


  sppb-db:
    image: mariadb
    restart: always
    volumes:
      - sppb_database:/var/lib/mysql
    networks:
      - LinkLocal
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD:  ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - LinkLocal
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=sppb-db

networks:
  LinkLocal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  sppb_database: